name: New charts
description: Request charts
title: '[Playbook]: '
labels: ['playbook', 'new', 'good first issue', 'hacktoberfest']
assignees:
  - drph4nt0m
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: country
    attributes:
      label: Country
      description: What country charts are you requesting?
      placeholder: India (IN)
    validations:
      required: true
  - type: input
    id: eaip
    attributes:
      label: eAIP
      description: Country eAIP website
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to add a new playbook
      value: |
        You can check [playbooks](https://github.com/drph4nt0m/avbot-charts/tree/main/playbooks) for examples on chart playbooks and [axios engine](https://github.com/drph4nt0m/avbot-charts/blob/main/app/engines/axios.js) on how the features in the playbook are used by the axios scraping engine.

        Tasks summary:
        -[ ] Fork & clone AvBot Charts
        -[ ] Create playbook for the country in playbooks
        -[ ] Add tests for the country in tests/getChart.test.js (tests should be in alphabetical order of the country code)
        -[ ] Push changes and submit a pull request
        -[ ] If you need any help, reach out to us on our [Discord server](http://link.avbot.in/support).

        Are you ready to work on this issue? Let us know, and we will assign it to you.

        Happy Coding!
